apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
        - name: api1
          image: docker.io/library/postgres-api1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
